seed: 40 # 40 - 49
device: "cuda:0"            # "cuda" or "cpu"
train:
  epochs: 30000
  batch:
    n_f: 8192             # collocation points
  optimizer:
    name: adam
    lr: 1.0e-3
  loss_weights:
    res: 1.0    # PDE residual
    data: 1.0  # data loss
log:
  out_dir: "analysis/results/runs"
  wandb:
    enabled: true
    project: "naPINN_AllenCahn_v1"
    entity: null      # or your team
    mode: "online"      # "auto" | "offline" | "disabled"
eval:
  grid:
    nx: 120
    ny: 120
    nt: 120
  every: 1000
